# Generated by Django 4.2.5 on 2023-11-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_description', models.TextField(max_length=1000)),
                ('receipe_image', models.FileField(upload_to='')),
                ('receipe_amount', models.IntegerField(default=200)),
            ],
        ),
    ]
