# Generated by Django 4.2.5 on 2023-11-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_receipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
